import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowRight, Building2, CheckCircle2, ChevronLeft, ChevronRight, Home, MoreVertical, Plus, RotateCcw, Search, Upload, UserCheck, UserPlus, Users, Zap } from "lucide-react";
import { useDeferredValue, useState } from "react";
import { Link } from "react-router-dom";
import { ApiError, archiveStudent, getAcademicReference, getDashboardSummary, getStudents, getStudentStats } from "../../lib/api";

const formatAttendance = (value: number | null) => value == null ? "—" : `${value.toFixed(1).replace(".0", "")}%`;

export function StudentsPage() {
  const client = useQueryClient();
  const [search, setSearch] = useState("");
  const [yearGroupId, setYearGroupId] = useState("");
  const [formGroupId, setFormGroupId] = useState("");
  const [houseId, setHouseId] = useState("");
  const [status, setStatus] = useState("");
  const [page, setPage] = useState(1);
  const [menuId, setMenuId] = useState<string | null>(null);
  const deferredSearch = useDeferredValue(search.trim());
  const filters = { yearGroupId, formGroupId, houseId, status };
  const students = useQuery({ queryKey: ["students", deferredSearch, page, filters], queryFn: () => getStudents(deferredSearch, page, 10, filters) });
  const stats = useQuery({ queryKey: ["student-stats"], queryFn: getStudentStats });
  const reference = useQuery({ queryKey: ["academic-reference"], queryFn: getAcademicReference });
  const dashboard = useQuery({ queryKey: ["dashboard-summary"], queryFn: getDashboardSummary });
  const archiveRecord = useMutation({ mutationFn: archiveStudent, onSuccess: async () => { setMenuId(null); await Promise.all([client.invalidateQueries({ queryKey: ["students"] }), client.invalidateQueries({ queryKey: ["student-stats"] })]); } });
  const rows = students.data?.items ?? [];
  const values = stats.data ?? { total: 0, active: 0, applicants: 0, archived: 0 };
  const metrics = [
    { label: "Total Students", value: values.total, note: "All enrolled students", icon: Users, tone: "amber" },
    { label: "Active Students", value: values.active, note: "Currently active", icon: UserCheck, tone: "green" },
    { label: "New This Term", value: dashboard.data?.students.newThisTerm ?? 0, note: "Added in the current term", icon: UserPlus, tone: "blue" },
    { label: "Pending Actions", value: values.applicants, note: "Require attention", icon: Archive, tone: "red" },
  ];
  const availableForms = reference.data?.formGroups.filter((item) => !yearGroupId || item.yearGroupId === yearGroupId) ?? [];
  const resetFilters = () => { setSearch(""); setYearGroupId(""); setFormGroupId(""); setHouseId(""); setStatus(""); setPage(1); };

  return <div className="admin-page-container">
    <div className="breadcrumb-nav"><Home size={14}/><span>Students</span></div>
    <div className="admin-page-header"><div className="admin-page-title-group"><h1>Students</h1><p>Manage learner records, enrolment, attendance and academic information.</p></div><div className="admin-header-actions"><button className="secondary-button" disabled title="Bulk import will be enabled with the import workflow"><Upload size={17}/> Import Students</button><Link className="primary-button" to="/students/new"><Plus size={17}/> Add Student</Link></div></div>
    <section className="kpi-cards-grid" aria-label="Student statistics">{metrics.map(({ label, value, note, icon: Icon, tone }) => <article className="kpi-card" key={label}><div className="kpi-card-top"><div className={`kpi-icon-wrap ${tone}`}><Icon size={21}/></div><div className="kpi-data-wrap"><span className="kpi-label">{label}</span><span className="kpi-value">{stats.isLoading ? "—" : value}</span><small>{note}</small></div></div></article>)}</section>
    <div className="students-columns-layout"><section className="students-directory-card"><div className="directory-card-title"><Users size={18}/><h2>Student Directory</h2></div>
      <div className="directory-filter-toolbar"><div className="search-reset-row"><div className="search-input-box"><Search size={17}/><input type="search" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search by name or admission number..."/></div><button className="reset-filters-btn" onClick={resetFilters}><RotateCcw size={14}/> Reset Filters</button></div><div className="filters-dropdown-row"><select className="filter-select" value={yearGroupId} onChange={(event) => { setYearGroupId(event.target.value); setFormGroupId(""); setPage(1); }}><option value="">All Years</option>{reference.data?.yearGroups.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select className="filter-select" value={formGroupId} onChange={(event) => { setFormGroupId(event.target.value); setPage(1); }}><option value="">All Forms</option>{availableForms.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select className="filter-select" value={houseId} onChange={(event) => { setHouseId(event.target.value); setPage(1); }}><option value="">All Houses</option>{reference.data?.houses.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select className="filter-select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All Statuses</option><option value="ACTIVE">Active</option><option value="APPLICANT">Applicant</option><option value="WITHDRAWN">Withdrawn</option><option value="GRADUATED">Graduated</option><option value="ARCHIVED">Archived</option></select></div></div>
      {students.isError ? <div className="empty-state compact"><Archive size={30}/><h2>Student records are unavailable</h2><p>{students.error instanceof ApiError ? students.error.message : "The directory could not be loaded."}</p><button className="secondary-button" onClick={() => void students.refetch()}>Retry</button></div> : <div className="data-table-wrap"><table className="data-table student-directory-table"><thead><tr><th>Student</th><th>Admission No.</th><th>Year / Form</th><th>House</th><th>Attendance</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{students.isLoading && <tr><td colSpan={7}>Loading learner records...</td></tr>}{rows.map((student) => { const enrolment = student.enrollments[0]; return <tr key={student.id}><td><div className="student-identity-cell"><span className="student-avatar-badge blue">{student.firstName[0]}{student.lastName[0]}</span><strong>{student.firstName} {student.lastName}</strong></div></td><td className="mono">{student.admissionNumber}</td><td>{enrolment ? `${enrolment.yearGroup.name}${enrolment.formGroup ? ` / ${enrolment.formGroup.name}` : ""}` : "Not enrolled"}</td><td>{enrolment?.house?.name ?? "—"}</td><td><strong className="attendance-value">{formatAttendance(student.attendancePercentage)}</strong></td><td><span className={`status-pill ${student.status === "ACTIVE" ? "green" : "neutral"}`}><i/>{student.status[0]}{student.status.slice(1).toLowerCase()}</span></td><td style={{ position: "relative" }}><button className="icon-button" onClick={() => setMenuId(menuId === student.id ? null : student.id)} aria-label={`Actions for ${student.firstName} ${student.lastName}`}><MoreVertical size={17}/></button>{menuId === student.id && <div className="dropdown-menu-popover" style={{ right: 8, top: 40 }}><button className="dropdown-menu-item danger" onClick={() => { if (window.confirm(`Archive ${student.firstName} ${student.lastName}?`)) archiveRecord.mutate(student.id); }}>Archive student</button></div>}</td></tr>; })}</tbody></table>{!students.isLoading && rows.length === 0 && <div className="empty-state compact"><Search size={28}/><h2>No learner records found</h2><p>Adjust the filters or register a new student.</p></div>}</div>}
      <div className="table-footer"><span>Showing {rows.length} of {students.data?.pagination.total ?? 0} students</span><div><button className="pagination-button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)} aria-label="Previous page"><ChevronLeft size={16}/></button><span className="page-number">{page}</span><button className="pagination-button" disabled={page >= (students.data?.pagination.pages ?? 1)} onClick={() => setPage((value) => value + 1)} aria-label="Next page"><ChevronRight size={16}/></button></div></div>
    </section><aside className="quick-student-actions-card"><h2><Zap size={18}/> Quick Student Actions</h2><div className="action-cards-stack"><Link className="quick-action-tile" to="/students/new"><span className="quick-tile-icon red"><UserPlus/></span><span className="quick-tile-text"><strong>Add Student</strong><small>Create a new student record</small></span><ArrowRight size={16}/></Link><button className="quick-action-tile" disabled title="Bulk import workflow is not configured"><span className="quick-tile-icon green"><Upload/></span><span className="quick-tile-text"><strong>Import Students</strong><small>Bulk import student records</small></span><ArrowRight size={16}/></button><Link className="quick-action-tile" to="/academics"><span className="quick-tile-icon blue"><Users/></span><span className="quick-tile-text"><strong>View Year Groups</strong><small>Manage year group settings</small></span><ArrowRight size={16}/></Link><Link className="quick-action-tile" to="/academics"><span className="quick-tile-icon purple"><Building2/></span><span className="quick-tile-text"><strong>Manage Forms</strong><small>Create and manage forms</small></span><ArrowRight size={16}/></Link></div></aside></div>
    <div className="policy-info-bar"><CheckCircle2 size={15}/> Student records are archived rather than deleted when linked historical records exist.</div>
  </div>;
}
